import { test, expect } from 'bun:test'
import { readFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { loadEmbeddedAssets } from '@/exe/assets'

const srcDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'src')
const exeDir = join(srcDir, 'exe')

/**
 * Spec B 接缝 4 兜底断言。launcher 无法被 `bun test` 真正编译实跑（需
 * `bun build --compile`），故靠源码层文本断言锁 loadEmbeddedAssets 的形状契约
 * （Ruling-A/B：统一对象含 indexHtml/assets/pluginJs/pluginPkg）。Ruling-C 选
 * manifest 回退路径后，assets.ts 不再含 `with` 资产导入语法——额外断言 manifest
 * 回退路径的接线标记，确保未来若误改回 directory import 会即红。
 */
test('src/exe/assets.ts 存在并暴露 loadEmbeddedAssets（Ruling-A/B 形状）', () => {
  const p = join(exeDir, 'assets.ts')
  expect(existsSync(p)).toBe(true)
  const src = readFileSync(p, 'utf-8')
  expect(src).toContain('export async function loadEmbeddedAssets')
  expect(src).toContain('indexHtml')
  expect(src).toContain('assets')
  expect(src).toContain('pluginJs')
  expect(src).toContain('pluginPkg')
  // EmbeddedAssets 接口四字段齐备
  expect(src).toContain('export interface EmbeddedAssets')
})

test('assets.ts 走 manifest 回退路径（Ruling-C），不含 directory import 语句', () => {
  const src = readFileSync(join(exeDir, 'assets.ts'), 'utf-8')
  // manifest 回退接线标记
  expect(src).toContain("from './manifest'")
  expect(src).toContain('ASSET_FILES')
  // directory import 在 Bun 1.3.14 编译失败，不得复活为实际 import 语句
  // （注释里解释为何弃用的措辞不算——只锁 import 行）。
  const importLines = src.split('\n').filter((l) => /^\s*import\b/.test(l))
  for (const l of importLines) {
    expect(l).not.toMatch(/type:\s*['"]directory['"]/)
  }
})

test('manifest.ts 由 gen-manifest.ts 生成并含四段资产', () => {
  const p = join(exeDir, 'manifest.ts')
  expect(existsSync(p)).toBe(true)
  const src = readFileSync(p, 'utf-8')
  expect(src).toContain('AUTO-GENERATED by scripts/gen-manifest.ts')
  expect(src).toContain('export const INDEX_HTML: string =')
  expect(src).toContain('export const ASSET_FILES: [string, string][] =')
  expect(src).toContain('export const PLUGIN_JS: string =')
  expect(src).toContain('export const PLUGIN_PKG: string =')
})

/**
 * 功能性 round-trip：assets.ts 在 dev 下可直接 import（manifest 是普通 TS
 * 模块），故可实跑 loadEmbeddedAssets() 验字节级正确——比纯源码断言更强。
 * 锁定：index.html 文本、assets key 形如 assets/<file> 且字节与 dist 一致、
 * pluginJs 含 __MEMSIDE_PORT__ 占位（安装时烘焙）、pluginPkg 是合法 JSON 文本。
 */
test('loadEmbeddedAssets() 装配统一对象，字节级匹配 dist + 插件源', async () => {
  const ea = await loadEmbeddedAssets()

  // index.html
  const idxOrig = readFileSync(join(srcDir, 'web', 'dist', 'index.html'), 'utf-8')
  expect(ea.indexHtml).toBe(idxOrig)

  // assets：key 形如 assets/<file>，字节与磁盘 dist 一致
  for (const [key, bytes] of Object.entries(ea.assets)) {
    expect(key).toMatch(/^assets\//)
    const orig = readFileSync(join(srcDir, 'web', 'dist', key))
    expect(bytes).toBeInstanceOf(Uint8Array)
    expect(bytes.byteLength).toBe(orig.byteLength)
    // 字节级比对
    let identical = orig.byteLength === bytes.byteLength
    for (let i = 0; i < bytes.length && identical; i++) {
      if (orig[i] !== bytes[i]) identical = false
    }
    expect(identical).toBe(true)
  }

  // pluginJs：含端口占位（installOpencodePlugin 烘焙依赖）
  const pjOrig = readFileSync(join(srcDir, '..', 'opencode-plugin', 'memside.js'), 'utf-8')
  expect(ea.pluginJs).toBe(pjOrig)
  expect(ea.pluginJs).toContain('__MEMSIDE_PORT__')

  // pluginPkg：JSON 文本字符串（非解析对象），写盘前可 JSON.parse
  const ppOrig = readFileSync(join(srcDir, '..', 'opencode-plugin', 'package.json'), 'utf-8')
  expect(ea.pluginPkg).toBe(ppOrig)
  expect(typeof ea.pluginPkg).toBe('string')
  expect(JSON.parse(ea.pluginPkg).name).toBe('memside-opencode')
})
