import { test, expect } from 'bun:test'
import { readFileSync, existsSync, mkdtempSync, mkdirSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { assembleAssets, loadEmbeddedAssets, type Manifest } from '@/exe/assets'

const srcDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'src')
const exeDir = join(srcDir, 'exe')

/**
 * Spec B 接缝 4 兜底断言。launcher 无法被 `bun test` 真正编译实跑（需
 * `bun build --compile`），故靠源码层文本断言锁 loadEmbeddedAssets 的形状契约
 * （Ruling-A/B：统一对象含 indexHtml/assets/pluginJs/pluginPkg）。Ruling-C 选
 * manifest 回退路径后，assets.ts 不再含 `with` 资产导入语法——额外断言 manifest
 * 回退路径的接线标记，确保未来若误改回 directory import 会即红。
 */
test('src/exe/assets.ts 存在并暴露 loadEmbeddedAssets（Ruling-A/B 形状）', () => {
  const p = join(exeDir, 'assets.ts')
  expect(existsSync(p)).toBe(true)
  const src = readFileSync(p, 'utf-8')
  expect(src).toContain('export async function loadEmbeddedAssets')
  expect(src).toContain('indexHtml')
  expect(src).toContain('assets')
  expect(src).toContain('pluginJs')
  expect(src).toContain('pluginPkg')
  // EmbeddedAssets 接口四字段齐备
  expect(src).toContain('export interface EmbeddedAssets')
})

test('assets.ts 走 manifest 回退路径（Ruling-C），不含 directory import 语句', () => {
  const src = readFileSync(join(exeDir, 'assets.ts'), 'utf-8')
  // manifest 回退接线标记
  expect(src).toContain("from './manifest'")
  expect(src).toContain('ASSET_FILES')
  // directory import 在 Bun 1.3.14 编译失败，不得复活为实际 import 语句
  // （注释里解释为何弃用的措辞不算——只锁 import 行）。
  const importLines = src.split('\n').filter((l) => /^\s*import\b/.test(l))
  for (const l of importLines) {
    expect(l).not.toMatch(/type:\s*['"]directory['"]/)
  }
})

/**
 * Spec B 接缝 3 兜底断言。launcher 无法被 `bun test` 真正编译实跑（需
 * `bun build --compile`），故靠源码层文本断言锁接线：必须调 startDaemon
 * （含 serveStaticAssets）、installOpencodePlugin（含 files）、loadEmbeddedAssets
 * （Task 4 统一资产对象，Ruling-A/B 废弃 brief 的动态 import 插件块）、
 * findPortHolders（port-check 复用）。任一 token 缺失即红，防止未来 refactor
 * 误断 launcher 的启动链路。
 */
test('src/exe/launcher.ts 存在并接线启动链路（Ruling-A/B 统一资产对象）', () => {
  const p = join(exeDir, 'launcher.ts')
  expect(existsSync(p)).toBe(true)
  const src = readFileSync(p, 'utf-8')
  expect(src).toContain('startDaemon')
  expect(src).toContain('serveStaticAssets')
  expect(src).toContain('installOpencodePlugin')
  expect(src).toContain('files')
  expect(src).toContain('loadEmbeddedAssets')
  expect(src).toContain('findPortHolders')
  // Ruling-A/B：插件资产从统一对象取，不得复活 brief 的动态 import 插件源块。
  // 仅锁 import 行（注释里的措辞不算），与 assets.ts 的 directory-import 锁法一致。
  const importLines = src.split('\n').filter((l) => /^\s*import\b/.test(l))
  for (const l of importLines) {
    expect(l).not.toMatch(/@ts-expect-error/)
    expect(l).not.toMatch(/opencode-plugin\/memside\.js/)
  }
  // 整源不得有动态 import() 插件源（brief 的废弃写法）。
  expect(src).not.toMatch(/import\(['"].*opencode-plugin\/memside\.js['"]\)/)
})

test('manifest.ts 由 gen-manifest.ts 生成并含四段资产', () => {
  const p = join(exeDir, 'manifest.ts')
  expect(existsSync(p)).toBe(true)
  const src = readFileSync(p, 'utf-8')
  expect(src).toContain('AUTO-GENERATED by scripts/gen-manifest.ts')
  expect(src).toContain('export const INDEX_HTML: string =')
  expect(src).toContain('export const ASSET_FILES: [string, string][] =')
  expect(src).toContain('export const PLUGIN_JS: string =')
  expect(src).toContain('export const PLUGIN_PKG: string =')
})

/**
 * 功能性 round-trip：assembleAssets 是纯函数（相对 Bun 运行时），相同 manifest
 * 产出相同 EmbeddedAssets。本测试用自造 tmp fixture 喂它——**不读磁盘 dist、
 * 不读 git manifest、不跑 gen-manifest**，彻底切断「进 git 的 manifest」与
 * 「不进 git 的 dist」的脱节依赖（root cause：两者本就是两次独立命令产物）。
 *
 * 锁定：index.html 文本透传、assets base64 解码二进制安全（含非 ASCII 字节）、
 * pluginJs 含 __MEMSIDE_PORT__ 占位（安装时烘焙）、pluginPkg 是合法 JSON 文本。
 */
test('assembleAssets() 装配统一对象，字节级匹配自造 fixture（自给自足，不读磁盘 dist）', () => {
  // 自造 tmp 目录 + fixture（不跑 gen-manifest，不读磁盘 dist）。
  const tmpRoot = mkdtempSync(join(tmpdir(), 'memside-asset-'))
  const tmpIndex = join(tmpRoot, 'index.html')
  const tmpAssetsDir = join(tmpRoot, 'assets')
  const tmpJs = join(tmpAssetsDir, 'x.js')
  const tmpPluginJs = join(tmpRoot, 'memside.js')
  const tmpPluginPkg = join(tmpRoot, 'package.json')

  const indexHtmlContent =
    '<!doctype html><html><head><title>TEST</title></head><body><div id="root"></div></body></html>'
  // 含非 ASCII（中文 + emoji），验 base64 解码二进制安全。
  const jsContent = '你好世界 🌍 console.log(1)'
  const pluginJsContent = 'const P = "__MEMSIDE_PORT__";'
  const pluginPkgContent = '{"name":"memside-opencode","version":"1.0.0"}'

  mkdirSync(tmpAssetsDir, { recursive: true })
  writeFileSync(tmpIndex, indexHtmlContent, 'utf-8')
  writeFileSync(tmpJs, jsContent, 'utf-8')
  writeFileSync(tmpPluginJs, pluginJsContent, 'utf-8')
  writeFileSync(tmpPluginPkg, pluginPkgContent, 'utf-8')

  // 构 Manifest 对象（直接用刚写的 tmp 文件内容，不读 src/web/dist、不读 git manifest）。
  const manifest: Manifest = {
    INDEX_HTML: readFileSync(tmpIndex, 'utf-8'),
    ASSET_FILES: [['assets/x.js', readFileSync(tmpJs).toString('base64')]],
    PLUGIN_JS: readFileSync(tmpPluginJs, 'utf-8'),
    PLUGIN_PKG: readFileSync(tmpPluginPkg, 'utf-8'),
  }

  const ea = assembleAssets(manifest)

  // index.html 文本透传
  expect(ea.indexHtml).toBe(manifest.INDEX_HTML)
  expect(ea.indexHtml).toBe(indexHtmlContent)

  // assets：base64 解码为 Uint8Array，字节级匹配 tmp 原始字节（含非 ASCII）
  const jsBytes = ea.assets['assets/x.js']
  expect(jsBytes).toBeInstanceOf(Uint8Array)
  const origJsBuf = Buffer.from(readFileSync(tmpJs))
  expect(jsBytes.byteLength).toBe(origJsBuf.byteLength)
  // 逐字节比对（Buffer 是 Uint8Array 子类，直接比较底层字节）
  expect(Buffer.from(jsBytes)).toEqual(origJsBuf)
  // 显式验非 ASCII 字节确实存活（你好世界 🌍 的 UTF-8 字节非全 ASCII）
  const decodedBack = Buffer.from(jsBytes).toString('utf-8')
  expect(decodedBack).toBe(jsContent)
  expect(decodedBack).toContain('你好世界')
  expect(decodedBack).toContain('🌍')

  // pluginJs：透传 + 含端口占位（installOpencodePlugin 烘焙依赖）
  expect(ea.pluginJs).toBe(manifest.PLUGIN_JS)
  expect(ea.pluginJs).toBe(pluginJsContent)
  expect(ea.pluginJs).toContain('__MEMSIDE_PORT__')

  // pluginPkg：JSON 文本字符串（非解析对象），写盘前可 JSON.parse
  expect(ea.pluginPkg).toBe(manifest.PLUGIN_PKG)
  expect(typeof ea.pluginPkg).toBe('string')
  expect(JSON.parse(ea.pluginPkg).name).toBe('memside-opencode')
})
