#!/usr/bin/env bun
/**
 * Spec B 接缝 4 资产清单生成器（Ruling-C 回退路径）。
 *
 * 实测 Bun 1.3.14 的 `with { type: 'directory' }` directory import 在
 * `bun build --compile` 下报 "Could not resolve"（见 task-4-report.md），
 * `with { type: 'file' }` 落回 text（非 BunFile 句柄），无法拿 Uint8Array。
 * 故采用构建期 manifest 回退：本脚本枚举 src/web/dist/ + opencode-plugin/
 * 的文件，读成 base64/文本常量写进 src/exe/manifest.ts，assets.ts import 它。
 *
 * 资产文件（assets/*）用 base64 内嵌——二进制安全，覆盖未来 png/font/svg 等。
 * index.html / pluginJs / pluginPkg 是已知文本，直接转义字符串内嵌（无 33% 膨胀）。
 *
 * 运行：`bun run scripts/gen-manifest.ts`。Task 6 会把它前置进 build:exe。
 * 本 task 不改 package.json——Task 6 接线。
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const distDir = join(root, 'src', 'web', 'dist')
const pluginDir = join(root, 'opencode-plugin')
const outPath = join(root, 'src', 'exe', 'manifest.ts')

/** JSON.stringify 产出合法 TS 字符串字面量。 */
function esc(s: string): string {
  return JSON.stringify(s)
}

const lines: string[] = []
lines.push('// AUTO-GENERATED by scripts/gen-manifest.ts — do not edit by hand.')
lines.push('// Spec B 接缝 4：把 src/web/dist/ + opencode-plugin/ 内嵌进 bun build --compile exe。')
lines.push('// 由 Task 6 的 build:exe 前置步骤（bun run scripts/gen-manifest.ts）重生。')
lines.push('// 删除/重生命令前勿手改。')
lines.push('')

// index.html —— 文本，直接转义。
const indexPath = join(distDir, 'index.html')
lines.push(`export const INDEX_HTML: string = ${esc(readFileSync(indexPath, 'utf-8'))}`)
lines.push('')

// assets/* —— base64 内嵌（二进制安全）。
lines.push('// [key, base64]；base64 覆盖二进制资产（png/font 等）。key 形如 assets/x.js。')
lines.push('export const ASSET_FILES: [string, string][] = [')
const assetsDir = join(distDir, 'assets')
let assetCount = 0
try {
  const files = readdirSync(assetsDir).sort()
  for (const f of files) {
    const key = `assets/${f}`
    const b64 = readFileSync(join(assetsDir, f)).toString('base64')
    lines.push(`  [${esc(key)}, ${esc(b64)}],`)
    assetCount++
  }
} catch {
  // dist 无 assets/ 子目录（空构建）→ 空 map，不崩
}
lines.push(']')
lines.push('')

// opencode-plugin 两文件 —— 文本，转义。pluginPkg 保持 JSON 文本字符串
// （installOpencodePlugin.files['package.json'] 接收字符串写盘）。
lines.push(`export const PLUGIN_JS: string = ${esc(readFileSync(join(pluginDir, 'memside.js'), 'utf-8'))}`)
lines.push(`export const PLUGIN_PKG: string = ${esc(readFileSync(join(pluginDir, 'package.json'), 'utf-8'))}`)
lines.push('')

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, lines.join('\n'), 'utf-8')
console.log(`[gen-manifest] wrote ${outPath} (${assetCount} asset files, ${lines.join('\n').length} bytes)`)
